/**
 * Constants used throughout the application
 */

// Area of Law options for lawyer registration
export const AREA_OF_LAW_OPTIONS = [
    'Banking Law',
    'Civil Law',
    'Commercial Law',
    'Corporate & Business Law',
    'Legal Due Diligence',
    'Employment Law',
    'Trusts Law',
    'Dispute Resolution & Litigation',
    'Financing & Transaction Advisory',
    'Capital Markets & Financial Services',
    'Taxation',
    'Employment',
    'Family',
    'Real Estate and Property',
    'Intellectual Property and Technology',
    'Insolvency',
    'Criminal Law',
    'Intellectual Property Law',
    'Corporate Law',
    'Company Law',
    'Internet Law',
    'Financial Services',
    'Investment',
    'Consultancy',
    'Pharmaceutical Law',
    'Criminal Litigation',
    'Procurement Law',
    'Corporate & Advisory for SMEs',
    'Project Structuring',
    'White-Collar Crime',
    'Legal Consultancies',
    'Virtual Assets',
    'Commercial Litigation',
    'Personal Injury Cases',
    'Road Traffic Offences',
    'Dispute Resolution',
    'Mediation',
    'Drafting and Vetting of Contracts',
    'Global Business',
    'Legal Opinion',
    'Labour Issues Management',
    'Urban Law',
    'AML & Corporate Governance',
    'Land Law',
    'Domestic Violence',
    'Data Protection Law',
    'Land Encroachment Matters',
    'Divorce and Child Custody',
    'Labour Law',
    'Sale of Immovable Property & Debt Recovery',
    'Small Claims',
    'Extra-Judicial Matters (Including Affidavit, Notice)',
    'Debt Recovery',
    'Succession',
    'Industrial Law',
].sort(); // Sorted alphabetically for better UX

// Lawyer Category options
export const LAWYER_CATEGORY_OPTIONS = [
    'Barristers',
    'Attorneys',
    'Notary',
    'Corporate Legal Companies',
];
